runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /contact
  static_files: www/contact.html
  upload: www/contact.html

- url: /about
  static_files: www/about.html
  upload: www/about.html